name       : heaptrack
version    : 1.4.0
release    : 1
source     :
    - https://github.com/KDE/heaptrack/archive/refs/tags/v1.4.0.tar.gz : 3aeea57e040d863a1ef95c3208ff0f163474a8bd8e10d4ece5e5f2137ab6436c
license    : GPL-2.0-or-later
component  : system.utils
summary    : A heap memory profiler for Linux 
description: |
    Heaptrack traces all memory allocations and annotates these events with stack traces. Dedicated analysis tools then allow you to interpret the heap memory profile to:

        - find hotspots that need to be optimized to reduce the memory footprint of your application
        - find memory leaks, i.e. locations that allocate memory which is never deallocated
        - find allocation hotspots, i.e. code locations that trigger a lot of memory allocation calls
        - find temporary allocations, which are allocations that are directly followed by their deallocation
builddeps  : 
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(libunwind)
    - pkgconfig(libzstd)
    - pkgconfig(zlib)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdiagram-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemmodels-devel
    - libboost-devel
    - threadweaver-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
